### ISSUE TITLE
Error while creating conda environment

### ISSUE THREAD

**Issue by Deepika1498** [LS4GAN/uvcgan#10]
**This error shows up when I try to create the conda env.** 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - lame
  - libopus
  - libstdcxx-ng
  - x264
  - nettle
  - libidn2
  - gnutls
  - openh264
  - ld_impl_linux-64
  - libvpx
  - readline
  - libtasn1
  - libunistring
  - _openmp_mutex
  - gmp
  - libgomp
  - ncurses
  - python==3.7.11=h12debd9_0
  - libgcc-ng
**How to solve this error?**

**Comment by usert5432** [comment]
Hi @Deepika1498,

Thanks for reporting this issue! I have extracted this conda environment from the official pytorch container. So, the conda environment expects a number of packages that are typically present in the pytorch container, but absent on your system (e.g. `lame`, `libopus`, etc).

There can be a few solutions to the problem. One solution may be, is that you could try installing those packages to your system. Another possible solution, is that we could try recreating the conda environment from scratch, without the absent packages.

To better understand which of the approaches is easier, could you please elaborate on what operating system you are using?

**Comment by Deepika1498** [comment]
I had solved this by removing the version numbers on all the packages and installed them again . Thanks!
