### ISSUE TITLE
Runtime Error when training

### ISSUE THREAD

**Issue by Deepika1498** [LS4GAN/uvcgan#11]
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
![runtimeerror](https://user-images.githubusercontent.com/60127339/206891987-a625bc80-af88-408d-b8ad-c7518f0e387a.PNG)

**Comment by usert5432** [comment]
Hi @Deepika1498,

This error message looks a bit cryptic. Could you please also provide a screenshot, showing the previous lines of the error? They will help us to investigate the problem.

**Comment by Deepika1498** [comment]
This is solved . Thank you . I just had to add if name=='main' in the train.py
