### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [48, 1, 3, 3], expected input[64, 3, 256, 256] to have 1 channels, but got 3 channels instead.

### ISSUE THREAD

**Issue by Pudding-0503** [LS4GAN/uvcgan#17]
I am trying to do unpaired image to image translation on my own dataset, which consists of 256*256 eight-bit grayscale images.
I changed the 85: 'image_shape' : (3, 256, 256), to 'image_shape' : (1, 256, 256) in the bert_A2B-256.py file.
But at runtime I get this error RuntimeError: Given groups=1, weight of size [48, 1, 3, 3], expected input[64, 3, 256, 256] to have 1 channels, but got 3 channels instead.
What could be the cause of this error? Thank you very much!

**Comment by usert5432** [comment]
Hi @Pudding-0503,

Thank you for reporting this issue!

I think, this error message:
>  But at runtime I get this error RuntimeError: Given groups=1, weight of size [48, 1, 3, 3], expected input[64, 3, 256, 256] to have 1 channels, but got 3 channels instead.

indicates that the network was constructed correctly, and it expects grayscale images. However, the actual dataset is not grayscale, but has 3 color channels. To help us to find the source of this issue, could I ask you please to share the `data` configuration part of your `bert_A2B-256.py` file (or the file itself if it is possible) ?

**Comment by usert5432** [comment]
Thank you @Pudding-0503!

Your file looks good, and I can reproduce the problem! Let me see what we can do to fix it.

**Comment by usert5432** [comment]
Hi @Pudding-0503.

If this issue is still relevant -- we have added another dataset `cyclegan-v2`, which handles the grayscale images correctly. I think you can make the grayscale training work by modifying the `bert_A2B-256.py` and replacing
```
dataset' : 'cyclegan',
```
with
```
dataset' : 'cyclegan-v2',
```
