### ISSUE TITLE
I cannot reproduce the FID and KID reported in the paper

### ISSUE THREAD

**Issue by Pudding-0503** [LS4GAN/uvcgan#20]
Hello, sorry to bother you again! I tested the generator you gave on three datasets and two directions today, the selfie2anime test data is 100, and the two datasets of CelebA test images are 1000, and then use the torch_fidelity package to calculate the results.
I use the fake image path as input1, but test, real (1000) and train as input2 cannot reproduce the results of your paper, the FID value is above 30, only selfie2anime has achieved the results close to the paper.
Then I tested the cyclegan generator you gave, and the FID value was as high as 40 on the two tasks of CelebA.
What could be the reason for this? Is there something I'm doing wrong?

**Comment by usert5432** [comment]
Hi @Pudding-0503,

Thank you for sharing these interesting results!

>  What could be the reason for this? Is there something I'm doing wrong?

I think what we are observing is a manifestation of the bias of the FID calculation (e.g. Figure 1 of [this paper](https://arxiv.org/pdf/1801.01401.pdf)) . Essentially, FID scores are biased for small sample sizes (< 10k).

When we calculated FIDs for our paper we have used an entire test sample (~10-30k samples for the CelebA datasets). For the table, you have used much smaller sample sizes of 100 and 1000.

So, I do not think there is anything wrong per se, the difference in FID is just an effect of different sample sizes.

**Comment by usert5432** [comment]
>  That is, if I want to achieve results close to those reported in the paper, I need to generate translation images fake_a and fake_b for all images in testA and testB of the male2female and glasses datasets, and then use the fake image as input1, The train image is used as input2, is it correct to calculate FID and KID in this way?

Yes, but not quite. We did not use `train` images during the evaluation. We have only used `test` images. So, you would need to modify the command to use the `test` images instead, e.g.:

```bash
fidelity --gpu 0 --fid --kid \
   --input1 ./banchmark_result/CycleGAN_glasses_pretrain/rmvGlasses/test_latest/fake_images/ \
   --input2 ./datasets/celeba_glasses/testB/ --kid-subset-size 1000
```
