### ISSUE TITLE
Preprocessed CelebA is gone

### ISSUE THREAD

**Issue by usert5432** [LS4GAN/uvcgan#22]
The preprocessed CelebA datasets are no longer available. This makes it impossible to reproduce the results of our paper.

In particular, these links are dead:

```
https://cgm.technion.ac.il/Computer-Graphics-Multimedia/CouncilGAN/DataSet/celeba_male2female.zip
https://cgm.technion.ac.il/Computer-Graphics-Multimedia/CouncilGAN/DataSet/celeba_glasses.zip
```

These datasets are provided by the CouncilGAN paper/repo [link](https://github.com/Onr/Council-GAN/blob/master/scripts/download.sh).

The datasets were not cached by webarchive. I can see a few possible solutions:
1. I can reupload their copies somewhere, but such an action may violate the datasets' copyright.
2. I can contact the paper authors and ask them to reupload, or grant us the permission to reupload without breaching any copyright. 

Linked issue: https://github.com/LS4GAN/uvcgan/issues/21

@brettviren and @YHRen could I ask your opinion about how to proceed regarding this issue please?

**Comment by YHRen** [comment]
@usert5432  

Thanks a lot for looking into this.

I would submit an issue in [council-GAN](https://github.com/Onr/Council-GAN) and cross-ref our issue with that one, so they are aware. You may want to `@` the author of that repo. 

I'm not sure about the copyright. I guess we can wait a little bit to see if they re-host it or not. 

Maybe after the paper submission, we can work more on how to recreate those images from the original ones, and share the scripts instead.

**Comment by usert5432** [comment]
Thank you, @YHRen! I have opened the issue in the upstream repository.

> Maybe after the paper submission, we can work more on how to recreate those images from the original ones, and share the scripts instead.

Yep, if we can figure it out that would be better.

**Comment by usert5432** [comment]
@YHRen, after a bit of investigation, I have found out that the CouncilGAN's images are just one of the versions of the CelebA dataset. That is, ones does not need to do any image manipulation to obtain the CouncilGAN's datasets. One can simply download an alternative version of the CelebA dataset and split it into different directories.

I will work on creating a corresponding script and a set of instructions.

**Comment by YHRen** [comment]
@usert5432  Nice investigation work! Let me know how it goes. Thank you so much.

**Comment by usert5432** [comment]
Now, that we created a [way to reproduce the datasets](https://github.com/LS4GAN/celeba4cyclegan), we need to update the download script:
- [ ] update the download script
- [ ] update the README file
