### ISSUE TITLE
Questions about training time

### ISSUE THREAD

**Issue by AKIIIIIIIIIII** [LS4GAN/uvcgan#3]
Hello :)
There are a few questions. 
Because I'm not very clear about ViT and GAN.
How long it takes to train UVCGAN? 
Is it possible to train on a single GPU?
Thank you.

**Comment by usert5432** [comment]
Hello @AKIIIIIIIIIII,

>  How long it takes to train UVCGAN?

The style transfer part of the UVCGAN can be trained in about 2.5 days on a single A600 GPU. (please check our [benchmarking repository for details](https://github.com/LS4GAN/benchmarking#training-time-in-hours-comparison)).

>  Is it possible to train on a single GPU?

Yes. We trained our style transfer models in a single GPU. However, if you would like to perform generator pretraining, then it might take too much time with the default parameters on a single GPU.

**Comment by AKIIIIIIIIIII** [comment]
Okay, I see!
Thank you for your response :)

**Comment by abhinavkcs11** [comment]
@AKIIIIIIIIIII You can close this issue as this is resolved.
