### ISSUE TITLE
Train on my own datasets

### ISSUE THREAD

**Issue by HzFrancesca** [LS4GAN/uvcgan#30]
I now have 600 photos of the datasets. Their resolutions are all 1616x1232. Obviously, simply modifying the training py file will not work. The codes provided in the paper are all 256x256 (probably?). Do you have any good suggestions?I'm not familiar with this area, thank you very much.

It was not difficult for me to run the training portion of selfie2anime provided by the author.

**Comment by usert5432** [comment]
Hi @HzFrancesca,

To start, you can try using one of the available scripts with 256x256 resolution.

For example, the script at https://github.com/LS4GAN/uvcgan/blob/main/scripts/train/celeba/cyclegan_celeba_preproc-256.py automatically resizes images down to `256x256` when loading.
https://github.com/LS4GAN/uvcgan/blob/0932e776f0cb0be4e23e31aaf78d3921b9beddd6/scripts/train/celeba/cyclegan_celeba_preproc-256.py#L153-L162

If you format your dataset to match the CycleGAN structure and update the data `path` in the script
https://github.com/LS4GAN/uvcgan/blob/0932e776f0cb0be4e23e31aaf78d3921b9beddd6/scripts/train/celeba/cyclegan_celeba_preproc-256.py#L149-L151

you can try training a simple uvcgan on your dataset to see if it works. If successful, you can then experiment with different image sizes.

Let me know if you need more details on any specific step.

**Comment by HzFrancesca** [comment]
I realized that I seemed to misunderstand your code logic and made the wrong modifications, so it crashed when I ran the script.
Now it's getting better, thanks again!
