### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by iosky** [LS4GAN/uvcgan#5]
![image](https://user-images.githubusercontent.com/27005213/173808659-d0f9d4e9-03cb-4e53-99df-3c82be4b281d.png)
![image](https://user-images.githubusercontent.com/27005213/173808704-f233122e-307f-4260-b7a1-1774ee745ea9.png)

**Comment by usert5432** [comment]
Hi @iosky. Thank you for reporting this issue!

To better diagnose this problem, could you please provide the full command that your are trying to run?

**Comment by iosky** [comment]
this command
![image](https://user-images.githubusercontent.com/27005213/173963135-9bcc39b1-2ace-4404-8432-dbf3b5bdf2f9.png)
![image](https://user-images.githubusercontent.com/27005213/173963154-63e16dc1-f0f1-46f2-851a-743c6df473d2.png)

**Comment by iosky** [comment]
the file isn't changed, I just run this command and download dataset

**Comment by iosky** [comment]
the ouput have some mistake in windows 10, but I run this command in Linux, get same result. so I edit the file
![image](https://user-images.githubusercontent.com/27005213/173963835-c905cbb0-6ae2-4b95-9ab7-c603483302ef.png)
the output is corrected

**Comment by usert5432** [comment]
Thank you @iosky for the details! I think I have a guess about what is going on there.

The UVCGAN style transfer training has two modes -- one is training from scratch and another is *transfer* training starting from some other model. By default, UVCGAN tries to perform transfer training from a BERT-like model, that was pre-trained on the `selfie2anime` dataset.

However, in your case, the UVCGAN code could not find the pre-trained BERT-like model and crashed.

There are several ways this crash can be fixed. One way, as you correctly pointed out, would be to disable transfer training and train the style transfer model from scratch (by replacing `self` -> `none`). But, the training from scratch may give you worse quality results than transfer training.

The other way to fix this crash may be to download the pre-trained `selfie2anime` model from [zenodo](https://zenodo.org/record/6336010) (here is [direct link](https://zenodo.org/record/6336010/files/bert_anime2selfie.zip?download=1)). And unzip this archive to `outdir/selfie2anime`.

**Comment by iosky** [comment]
Thank you so much!
