### ISSUE TITLE
eval fail

### ISSUE THREAD

**Issue by iosky** [LS4GAN/uvcgan#6]
![image](https://user-images.githubusercontent.com/27005213/174540529-a752cd0c-c8f7-40e9-9aef-c5c92f5fa395.png)

**Comment by iosky** [comment]
![image](https://user-images.githubusercontent.com/27005213/174538829-800c248a-77c0-4f69-9144-059fa52b275f.png)
only change this and dataset
![image](https://user-images.githubusercontent.com/27005213/174538943-44e05904-c563-4778-8e0f-287192e01be8.png)

**Comment by iosky** [comment]
image size 1024x1024

**Comment by iosky** [comment]
my mistake, forgot change the setting about transform_val

**Comment by usert5432** [comment]
> my mistake, forgot change the setting about transform_val

No problem @iosky. Did you manage to fully resolve this issue?

**Comment by iosky** [comment]
Yes, I can do this by myself, sorry to bother you.

**Comment by abhinavkcs11** [comment]
Hey @iosky,
How did you resolve this issue?
