### ISSUE TITLE
Cant find config for VitUnetGenerator

### ISSUE THREAD

**Issue by sonnguyen129** [LS4GAN/uvcgan#7]
Hi @usert5432. Can you tell me the config param of VITUnetGEnerator?
Thank you so much.

**Comment by usert5432** [comment]
Hi @sonnguyen129. The training configuration of the `ViTUNetGenerator` is stored in the training files, e.g. training config for the CelebA dataset can be found in the training [script](https://github.com/LS4GAN/uvcgan/blob/main/scripts/train/celeba/cyclegan_celeba_preproc-256.py):
https://github.com/LS4GAN/uvcgan/blob/376439ae2a9be684ff279ddf634fe137aadc5df5/scripts/train/celeba/cyclegan_celeba_preproc-256.py#L81-L99

If you need the config for evaluation, then the pre-trained models and their configurations can be downloaded from [zenodo](https://zenodo.org/record/6336010).

I am not sure if that answers your question, so please let me know if you are referring to some other config?

**Comment by sonnguyen129** [comment]
Thanks for reply. I will reopen the issue if I have other questions.
